### ISSUE TITLE
[Feature][AI][Premium] Moderator

### ISSUE THREAD

**Issue by Qolzam** [Qolzam/react-social-network#104]
- [ ] Fraud content detection 
 - [ ] Fraud content detection (deep representation)  (Premium License)
 - [ ]  Fake user detection
 - [ ] Fake user detection (deep representation) (Premium License)
 - [ ] Moderator content rating
 - [ ] Moderator content rating (deep representation) (Premium License)
 - [ ] Appropriate content checking to spot out bad words
 - [ ] Controversy content detection based on pre-defined list of domain keywords (Premium License)
 - [ ] Fact checking to mark the content as reference requirement or non reference (Premium License)
