### ISSUE TITLE
[Feature][AI][Premium] Post Discovery

### ISSUE THREAD

**Issue by Qolzam** [Qolzam/react-social-network#95]
> For now this feature source code is private. We only show service availability status here. 

Understanding topics and keywords of user's contents.
- [ ] Implement model
- [ ] Verify model performance
- [ ] Report performance
- [ ] Integrate to Algolia
- [ ] Integrate to Elastic search 
- [ ] Integrate to React Social

**Comment by huynhnguyen** [comment]
hi Amir, 
It seems like I need write permission to update it.
can you grant that write permission to me.

**Comment by huynhnguyen** [comment]
understanding topics and keywords of user's contents.
