### ISSUE TITLE
[Feature][AI][Premium] User Discovery

### ISSUE THREAD

**Issue by Qolzam** [Qolzam/react-social-network#96]
> For now this feature source code is private. We only show service availability status here. 
Found the similarity between user profile.
- [ ] Implement model
- [ ] Verify model performance
- [ ] Report performance
- [ ] Integrate to Algolia
- [ ] Integrate to Elastic search 
- [ ] Integrate to React Social

**Comment by huynhnguyen** [comment]
predict the similarity among user profiles.
