### ISSUE TITLE
[Feature][AI][Premium] Location discovery

### ISSUE THREAD

**Issue by Qolzam** [Qolzam/react-social-network#99]
> For now this feature source code is private. We only show service availability status here. 

Recommend locations to users based on their activities. 
- [ ] Implement model
- [ ] Verify model performance
- [ ] Report performance
- [ ] Integrate to Algolia
- [ ] Integrate to Elastic search 
- [ ] Integrate to React Social
